const { z } = require("zod");

const WorkbookPlanSchema = z.object({
  sheets: z
    .array(
      z.object({
        name: z.string().min(1).max(31),
        columns: z.array(z.string()).min(1).max(100),
        rows: z.array(z.array(z.union([z.string(), z.number(), z.boolean(), z.null()]))).default([]),
      })
    )
    .min(1)
    .max(20),
  notes: z.array(z.string()).optional().default([]),
});

function normalizeWorkbookPlan(plan, documentContext) {
  const parsed = WorkbookPlanSchema.safeParse(plan);
  if (!parsed.success) {
    return createFallbackWorkbookPlan(documentContext);
  }

  return {
    sheets: parsed.data.sheets.map((sheet, index) => normalizeSheet(sheet, index)),
    notes: parsed.data.notes,
  };
}

function createFallbackWorkbookPlan(documentContext) {
  if (documentContext.tables?.length) {
    return {
      sheets: documentContext.tables.map((table, index) => tableToSheet(table, index)),
      notes: ["Generated without DeepSeek because no API key was configured or the model plan was invalid."],
    };
  }

  const inferredPlan = inferStructuredPlan(documentContext.text);
  if (inferredPlan) {
    return {
      ...inferredPlan,
      notes: ["Generated by local fallback rules because no DeepSeek API key was configured or the model plan was invalid."],
    };
  }

  const rows = documentContext.text
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line, index) => [index + 1, line]);

  return {
    sheets: [
      {
        name: "Extracted Text",
        columns: ["Line", "Content"],
        rows: rows.length ? rows : [[1, documentContext.text.trim()]],
      },
    ],
    notes: ["Generated without DeepSeek because no API key was configured or the model plan was invalid."],
  };
}

function inferStructuredPlan(text) {
  const normalized = text.replace(/\s+/g, " ").trim();
  return inferMeetingTasks(normalized) || inferCompanyRevenue(normalized);
}

function inferMeetingTasks(text) {
  const rows = [];

  for (const match of text.matchAll(/([\u4e00-\u9fa5A-Za-z]{2,10})负责([^，。]+)[，,](?:预计完成时间为|截止日期为|预计)([^。]+?)(?:完成)?[。.]/g)) {
    rows.push([match[1], match[2].trim(), match[3].trim()]);
  }

  for (const match of text.matchAll(/([\u4e00-\u9fa5A-Za-z]{2,10})进行([^，。]+)[，,](?:预计完成时间为|截止日期为|预计)([^。]+?)(?:完成)?[。.]/g)) {
    rows.push([match[1], match[2].trim(), match[3].trim()]);
  }

  if (!rows.length) {
    return null;
  }

  return {
    sheets: [
      {
        name: "Tasks",
        columns: ["负责人", "任务", "时间"],
        rows,
      },
    ],
  };
}

function inferCompanyRevenue(text) {
  const rows = [];
  const sentences = text.split(/[。.;；]/).map((sentence) => sentence.trim()).filter(Boolean);

  for (const sentence of sentences) {
    const company = sentence.match(/公司[A-Za-z0-9一二三四五六七八九十]+/)?.[0];
    const revenue = sentence.match(/(?:收入(?:达到了|为)?|则为)(\d+(?:\.\d+)?)\s*万元/)?.[1];
    const growth = sentence.match(/(?:同比增长|增长率为|仅为)(\d+(?:\.\d+)?)\s*%/)?.[1];

    if (company && revenue) {
      rows.push([company, Number(revenue), growth ? Number(growth) / 100 : ""]);
    }
  }

  if (!rows.length) {
    return null;
  }

  return {
    sheets: [
      {
        name: "Revenue",
        columns: ["公司", "收入（万元）", "增长率"],
        rows,
      },
    ],
  };
}

function tableToSheet(table, index) {
  const width = Math.max(...table.map((row) => row.length), 1);
  const firstRow = table[0] || [];
  const hasHeader = firstRow.some(Boolean) && table.length > 1;
  const columns = hasHeader ? padRow(firstRow, width).map((cell, i) => String(cell || `Column ${i + 1}`)) : makeColumns(width);
  const rows = (hasHeader ? table.slice(1) : table).map((row) => padRow(row, width));

  return normalizeSheet(
    {
      name: `Table ${index + 1}`,
      columns,
      rows,
    },
    index
  );
}

function normalizeSheet(sheet, index) {
  const columns = sheet.columns.map((column, columnIndex) => String(column || `Column ${columnIndex + 1}`));
  return {
    name: sanitizeSheetName(sheet.name || `Sheet ${index + 1}`),
    columns,
    rows: sheet.rows.map((row) => padRow(row.map(normalizeCell), columns.length)),
  };
}

function normalizeCell(value) {
  if (value === null || value === undefined) {
    return "";
  }
  return value;
}

function padRow(row, width) {
  const cells = row.slice(0, width);
  while (cells.length < width) {
    cells.push("");
  }
  return cells;
}

function makeColumns(width) {
  return Array.from({ length: width }, (_, index) => `Column ${index + 1}`);
}

function sanitizeSheetName(name) {
  const cleaned = String(name).replace(/[\][:*?/\\]/g, " ").replace(/\s+/g, " ").trim();
  return (cleaned || "Sheet").slice(0, 31);
}

module.exports = {
  createFallbackWorkbookPlan,
  normalizeWorkbookPlan,
};
